
package com.demo;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherInterface", targetNamespace = "http://sei.cxf/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherInterface {


    /**
     * 
     * @param city
     * @return
     *     returns java.util.List<com.demo.Weather>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWeatherByCity", targetNamespace = "http://sei.cxf/", className = "com.demo.GetWeatherByCity")
    @ResponseWrapper(localName = "getWeatherByCityResponse", targetNamespace = "http://sei.cxf/", className = "com.demo.GetWeatherByCityResponse")
    public List<Weather> getWeatherByCity(
        @WebParam(name = "city", targetNamespace = "")
        String city);

}
